### ISSUE TITLE
Is incanter necessary?

### ISSUE THREAD

**Issue by plexus** [MastodonC/kixi.stats#17]
kixi.stats has a `:dev` dependency on Incanter, however through transitive dependencies Incanter relies on a version of bouncycastle that no longer exists on Maven (see https://github.com/incanter/incanter/issues/388)

This causes issues under Clojure CLI, e.g. here you can see that Cljdoc is unable to build the docs for kixi.stats 0.4.1

https://circleci.com/gh/martinklepsch/cljdoc-builder/3024

This is partly a problem with cljdoc I think, Incanter has `<scope>test</scope>` in the kixi.stats pom, so it should probably ignore it

curl https://repo.clojars.org/kixi/stats/0.4.1/stats-0.4.1.pom

However doing a quick grep it seems incanter isn't actually used anywhere in the kixi.stats codebase. Is it necessary to have it in there?

**Comment by henrygarner** [comment]
@plexus thanks for the report. IIRC Incanter is left over from when I performed spot checks against various distributions. I’m pretty sure it can safely be removed though I won’t know for sure until I’m back at my desk later today

**Comment by plexus** [comment]
It can surely wait until then :) thanks for the quick response!

**Comment by henrygarner** [comment]
Incanter dependency has been removed in 0.4.2

**Comment by martinklepsch** [comment]
Docs for kixi.stats are now available on cljdoc: https://cljdoc.xyz/d/kixi/stats/0.4.2 🙂

**Comment by henrygarner** [comment]
@martinklepsch Excellent thanks! 🎉 Though makes me realise a local uncommitted file has made it into the Clojars artefact: https://cljdoc.xyz/d/kixi/stats/0.4.2/api/kixi.stats.params#Params 🤭
