### ISSUE TITLE
Rendering a histogram

### ISSUE THREAD

**Issue by Folcon** [MastodonC/kixi.stats#31]
Hi, just got introduced to this library and been digging around.

Is it possible to realise these histograms in some way? For rendering / visualisation for example?

Similar to what incanter does =)...

**Comment by henrygarner** [comment]
[Lambda Island](https://github.com/lambdaisland/ep43-data-science-kixi-stats/blob/master/src/ep43_data_science/graphs.clj#L95-L110) has produced sample code showing one way of binning data using kixi.stats. Once you have the binned data you can present it how you like. The linked code creates custom SVGs using the thi.ng libraries, but there are [many other options](https://scicloj.github.io/pages/libraries/#literate_programming_and_data_visualization)!

**Comment by Folcon** [comment]
Thank you =)...
