### ISSUE TITLE
simple-linear-regression documentation incorrect?

### ISSUE THREAD

**Issue by kovasap** [MastodonC/kixi.stats#38]
[Here](https://github.com/MastodonC/kixi.stats/blob/33626268e11238264421d6783ccbc03f9254d549/src/kixi/stats/core.cljc#L472) it says that `simple-linear-regression` returns a vector with `[offset slope]`, but when I run it like this:
```
(transduce identity (kixi/simple-linear-regression :var1 :var2) [{:var1 1 :var2 2} {:var1 1 :var2 3}])
```
I get this thing in my browser log:
```
#object[kixi.stats.estimate.t_kixi$stats$estimate27271]
```
and I cannot use `(first)` or `(last)` to get the offset and slope respectively.  Am I misunderstanding something about the transduce syntax perhaps?

**Comment by henrygarner** [comment]
Many thanks for reporting this, the docstring was outdated. The result you get is actually a `kixi.stats.protocols/PParamaterised` so can get the parameter vector by invoking `kixi.stats.protocols/parameters` on it.
